import "./globals.css";


export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
	// const t = await getDictionary(lang);	
	return (
		<html lang={params.lang}>
			<body>
				{children}
			</body>
		</html>
	);
}
